services:
  minerva:
    container_name: minerva
    image: myself/minerva:latest
    ports:
      - '3001:8080'
  wedcms:
    container_name: wedcms
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3000:3000'
    env_file:
      - apps/core/.env
    develop:
      watch:
        - action: sync
          path: ./apps/core/src
          target: /app/apps/core/src
        - action: sync+restart
          path: ./apps/core/views
          target: /app/apps/core/views
        - action: sync
          path: ./apps/core/public
          target: /app/apps/core/public
        - action: rebuild
          path: ./apps/core/package.json
    volumes:
      - ./apps/core/public/v14:/app/apps/core/public/v14
