/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthRoomsIndexRouteImport } from './routes/_auth/rooms/index'
import { Route as AuthRconIndexRouteImport } from './routes/_auth/rcon/index'
import { Route as AuthNewsIndexRouteImport } from './routes/_auth/news/index'
import { Route as AuthAnnouncementsIndexRouteImport } from './routes/_auth/announcements/index'
import { Route as AuthUsersUserIdRouteImport } from './routes/_auth/users/$userId'
import { Route as AuthNewsNewRouteImport } from './routes/_auth/news/new'
import { Route as AuthNewsNewsIdRouteImport } from './routes/_auth/news/$newsId'
import { Route as AuthAnnouncementsNewRouteImport } from './routes/_auth/announcements/new'
import { Route as AuthAnnouncementsAnnouncementIdRouteImport } from './routes/_auth/announcements/$announcementId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRoomsIndexRoute = AuthRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRconIndexRoute = AuthRconIndexRouteImport.update({
  id: '/rcon/',
  path: '/rcon/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNewsIndexRoute = AuthNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAnnouncementsIndexRoute = AuthAnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersUserIdRoute = AuthUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNewsNewRoute = AuthNewsNewRouteImport.update({
  id: '/news/new',
  path: '/news/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNewsNewsIdRoute = AuthNewsNewsIdRouteImport.update({
  id: '/news/$newsId',
  path: '/news/$newsId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAnnouncementsNewRoute = AuthAnnouncementsNewRouteImport.update({
  id: '/announcements/new',
  path: '/announcements/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAnnouncementsAnnouncementIdRoute =
  AuthAnnouncementsAnnouncementIdRouteImport.update({
    id: '/announcements/$announcementId',
    path: '/announcements/$announcementId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/announcements/$announcementId': typeof AuthAnnouncementsAnnouncementIdRoute
  '/announcements/new': typeof AuthAnnouncementsNewRoute
  '/news/$newsId': typeof AuthNewsNewsIdRoute
  '/news/new': typeof AuthNewsNewRoute
  '/users/$userId': typeof AuthUsersUserIdRoute
  '/announcements/': typeof AuthAnnouncementsIndexRoute
  '/news/': typeof AuthNewsIndexRoute
  '/rcon/': typeof AuthRconIndexRoute
  '/rooms/': typeof AuthRoomsIndexRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/users/': typeof AuthUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/announcements/$announcementId': typeof AuthAnnouncementsAnnouncementIdRoute
  '/announcements/new': typeof AuthAnnouncementsNewRoute
  '/news/$newsId': typeof AuthNewsNewsIdRoute
  '/news/new': typeof AuthNewsNewRoute
  '/users/$userId': typeof AuthUsersUserIdRoute
  '/announcements': typeof AuthAnnouncementsIndexRoute
  '/news': typeof AuthNewsIndexRoute
  '/rcon': typeof AuthRconIndexRoute
  '/rooms': typeof AuthRoomsIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/users': typeof AuthUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/_auth/announcements/$announcementId': typeof AuthAnnouncementsAnnouncementIdRoute
  '/_auth/announcements/new': typeof AuthAnnouncementsNewRoute
  '/_auth/news/$newsId': typeof AuthNewsNewsIdRoute
  '/_auth/news/new': typeof AuthNewsNewRoute
  '/_auth/users/$userId': typeof AuthUsersUserIdRoute
  '/_auth/announcements/': typeof AuthAnnouncementsIndexRoute
  '/_auth/news/': typeof AuthNewsIndexRoute
  '/_auth/rcon/': typeof AuthRconIndexRoute
  '/_auth/rooms/': typeof AuthRoomsIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements/$announcementId'
    | '/announcements/new'
    | '/news/$newsId'
    | '/news/new'
    | '/users/$userId'
    | '/announcements/'
    | '/news/'
    | '/rcon/'
    | '/rooms/'
    | '/settings/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements/$announcementId'
    | '/announcements/new'
    | '/news/$newsId'
    | '/news/new'
    | '/users/$userId'
    | '/announcements'
    | '/news'
    | '/rcon'
    | '/rooms'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/'
    | '/_auth/announcements/$announcementId'
    | '/_auth/announcements/new'
    | '/_auth/news/$newsId'
    | '/_auth/news/new'
    | '/_auth/users/$userId'
    | '/_auth/announcements/'
    | '/_auth/news/'
    | '/_auth/rcon/'
    | '/_auth/rooms/'
    | '/_auth/settings/'
    | '/_auth/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/rooms/': {
      id: '/_auth/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof AuthRoomsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/rcon/': {
      id: '/_auth/rcon/'
      path: '/rcon'
      fullPath: '/rcon/'
      preLoaderRoute: typeof AuthRconIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/news/': {
      id: '/_auth/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof AuthNewsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/announcements/': {
      id: '/_auth/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AuthAnnouncementsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/$userId': {
      id: '/_auth/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthUsersUserIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/news/new': {
      id: '/_auth/news/new'
      path: '/news/new'
      fullPath: '/news/new'
      preLoaderRoute: typeof AuthNewsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/news/$newsId': {
      id: '/_auth/news/$newsId'
      path: '/news/$newsId'
      fullPath: '/news/$newsId'
      preLoaderRoute: typeof AuthNewsNewsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/announcements/new': {
      id: '/_auth/announcements/new'
      path: '/announcements/new'
      fullPath: '/announcements/new'
      preLoaderRoute: typeof AuthAnnouncementsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/announcements/$announcementId': {
      id: '/_auth/announcements/$announcementId'
      path: '/announcements/$announcementId'
      fullPath: '/announcements/$announcementId'
      preLoaderRoute: typeof AuthAnnouncementsAnnouncementIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAnnouncementsAnnouncementIdRoute: typeof AuthAnnouncementsAnnouncementIdRoute
  AuthAnnouncementsNewRoute: typeof AuthAnnouncementsNewRoute
  AuthNewsNewsIdRoute: typeof AuthNewsNewsIdRoute
  AuthNewsNewRoute: typeof AuthNewsNewRoute
  AuthUsersUserIdRoute: typeof AuthUsersUserIdRoute
  AuthAnnouncementsIndexRoute: typeof AuthAnnouncementsIndexRoute
  AuthNewsIndexRoute: typeof AuthNewsIndexRoute
  AuthRconIndexRoute: typeof AuthRconIndexRoute
  AuthRoomsIndexRoute: typeof AuthRoomsIndexRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthAnnouncementsAnnouncementIdRoute: AuthAnnouncementsAnnouncementIdRoute,
  AuthAnnouncementsNewRoute: AuthAnnouncementsNewRoute,
  AuthNewsNewsIdRoute: AuthNewsNewsIdRoute,
  AuthNewsNewRoute: AuthNewsNewRoute,
  AuthUsersUserIdRoute: AuthUsersUserIdRoute,
  AuthAnnouncementsIndexRoute: AuthAnnouncementsIndexRoute,
  AuthNewsIndexRoute: AuthNewsIndexRoute,
  AuthRconIndexRoute: AuthRconIndexRoute,
  AuthRoomsIndexRoute: AuthRoomsIndexRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
